### PR TITLE
#112 and #105

### PR DESCRIPTION
**Pull request by mbalmer2016**
FIxed test discovery(#112) in vs2015 and test debugging(#105) in vs2015. In order to support visual studio 2015 I have had to upgrade the solution to vs2015. The solution can no longer be opened in 2013 but the plugin works in both.

### CODE REVIEW

**Comment by sriv** [comment]
Quick update: I am looking at the changes, but the appveyor build is broken. Am investigating the cause. 

We appreciate your contribution!

**Comment by sriv** [comment]
Another update:

I am able to build the pull request on my box but if I try to deploy the VSIX to VS 2013, I get the below exception:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'Microsoft.VisualStudio.Shell.14.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at Gauge.VisualStudio.Core.Helpers.GaugeDaemonHelper.StartGaugeAsDaemon(Project gaugeProject) at Gauge.VisualStudio.Core.Helpers.GaugeDaemonHelper.GetApiConnectionFor(Project project) at Gauge.VisualStudio.Model.Concept.GetAllConcepts() at Gauge.VisualStudio.Model.Project.GetGaugeImplementations(Project containingProject) at Gauge.VisualStudio.Model.Project.get_Implementations() at Gauge.VisualStudio.Model.Project.GetStepImplementation(ITextSnapshotLine line) at Gauge.VisualStudio.Highlighting.UnimplementedStepTagger.<GetTags>d__0.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__5.MoveNext() WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. 
```

I remember a similar scenario when adding VS 2015 support, things used to work on Developer box where we had both VS 2013 and VS 2015 installed. However users could have just one version installed. I can't recollect the source, but I remember reading somewhere in MSDN forums that the higher version of Visual Studios try to redirect binding to lower versions of VS SDK libraries, not the other way around. This is one reason why the solution is still using VS 2013.

If you have the time, could you please check at your end if the VSIX installs and runs well on a VS 2013 only machine?

**Comment by mbalmer2016** [comment]
I fixed this problem for VS 2015 as that's what we needed. I will try to come up with something so it builds on both.

**Comment by mbalmer2016** [comment]
I've added separate build configs for 2015 (Debug|Release) and 2013(Debug-2013|Release-2013). The only difference between the builds is that one points at Shell.14.0 and the other points at Shell.12.0 in Core.csproj

I've also added another line in build.ps1 to build each Release config, and therefore separate artifacts.

I do not have access to a VS2013-only machine so please let me know if this is suitable

**Comment by sriv** [comment]
So with separate build configs, it would mean making platform specific releases correct? One each for VS2013 and VS2015 right now. We would like to avoid that, as much as we can.

Me and @BugDiver  have been investigating #112 ourselves, and I believe we have a root cause. The culprit is the call to [`OutputPaneLogger.Debug`](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.Model/Specification.cs#L61)  when invoking [`Specification.GetAllSpecs`](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.Model/Specification.cs#L46).

- `OutputPaneLogger.Debug` call requires a reference to `Microsoft.VisualStudio.Shell.12.0`. 
- When invoked from [`TestDiscoverer`](https://github.com/getgauge/gauge-visualstudio/blob/master/Gauge.VisualStudio.TestAdapter/TestDiscoverer.cs#L58), the code is executed under the AppDomain of `vstest.discoveryengine.exe`
- Hence there is no redirect of `Microsoft.VisualStudio.Shell.12.0` to use `Microsoft.VisualStudio.Shell.14.0`
- The exception thrown is `FileNotFound`.
- Disabling the calls to `OutputPaneLogger.Debug` fixes the test discovery.

Also note that 4e761cec53f0e40a47c67bdb0008a3b783204b28 would allow opening the project in either VS2013 or VS2015. This is required since one can debug a VS plugin only in matching version of Visual Studio, i.e. one cannot debug a plugin deployed to VS2015 via VS2013 AFAIK.

Does this make sense to you? 

I will be pushing a fix to remove the calls to `OutputPaneLogger` methods (for TestAdapter code) and perhaps you can try and see if it works for your use cases. How does that sound?


If you are OK, I would like to merge parts of the pull request,  such as [this](https://github.com/getgauge/gauge-visualstudio/pull/131/commits/f06a7f03b9599cd69396f7a1da74ce68c10298a5#diff-4e111d733d33ef91bd35ca47bff0a589R32).

**Comment by mbalmer2016** [comment]
yeh that sounds great. Let me know when you have pushed the fix. Thanks

**Comment by sriv** [comment]
Have pushed https://github.com/getgauge/gauge-visualstudio/commit/05f9d7c6132802531a6cab01493cfb696720c5c5 against #112. You could check that or alternatively use the [appveyor artifact](https://ci.appveyor.com/project/sriv/gauge-visualstudio/build/1.0.50/artifacts). Please let us know how it goes. Thanks.

**Pull request closed without merging**
